import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { FaAngleRight, FaCheckCircle, FaDotCircle } from "react-icons/fa";
import { FaUserDoctor } from "react-icons/fa6";
import { FaCheck } from "react-icons/fa";
import { FaFlask } from "react-icons/fa";
import { FaBaby } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

export default function aboutUs() {
  return (
    <>
      <Head>
        <title>Jeevan Raksha - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="hero v-center about-inside pr">
          <div className="overlay-inside"></div>
          <div className="wrapper box-center jcs pr zi2">
            <div className="about-hero tac">
              <h1 className="fs38 fw7 mt8 fs30 fw7 lh24 fc4 mb32">About Us</h1>
              <ul className="df ttu box-center fc4">
                <li className="v-center mr16 fs14">
                  <Link href="/" previewlistener="true">
                    HOME
                  </Link>
                </li>
                <li>
                  <FaAngleRight />
                </li>
                <li className="v-center fs14 ml16">About</li>
              </ul>
            </div>
          </div>
        </div>
        <secion className="about-main-secion ">
          <div className="wrapper ptb48 df">
            <div className="about-faq flx48 br24 ofh mtb8">
              <img
                src="/images/about-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className=" w100"
              />
            </div>
            <div className="about-text pl48">
              <div className="about-content">
                <span className="about-sub-heading fs18 fc1 fw6 ">
                  Welcome to Jeevan Raksha Hospital
                </span>
                <h2 className="about-heading fs36 fw6 ptb24 lh48">
                  A Brief Overview of Jeevan Raksha Hospital
                </h2>
                <p className="about-desc lh30 v-center fc3 fs18 ">
                  At Jeevan Raksha Hospital, we're dedicated to providing
                  top-notch healthcare. Our team works tirelessly to give you
                  the best care possible. We focus on treating you with
                  compassion and using the latest medical advancements. Your
                  well-being is our priority.
                </p>
                <ul className="about-list lh30 pt24">
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Excellent Patient Care
                    Every Time
                  </li>
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Building Trusting
                    Patient Relationships
                  </li>
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Innovating for Better
                    Health Solutions
                  </li>
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Supporting Staff Growth
                    and Development
                  </li>
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Nurturing a Positive
                    Work Environment
                  </li>
                  <li className="v-center mb8">
                    <FaDotCircle className="fc1 mr8" /> Investing in Staff's
                    Professionalism
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </secion>
        <section className="our-vision-area ptb48">
          <div className="card-container wrapper df fww aisc">
            <div className="card flx33 mb16 df">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16 ">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Delivering compassionate, high-quality healthcare services to
                  our community, ensuring every patient receives exceptional
                  care tailored to their needs and fosters a sense of
                  well-being.
                </p>
              </div>
            </div>
            <div className="card flx33 mb16 df">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Vision</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Striving to become the premier healthcare provider in the
                  region, renowned for our dedication to excellence and
                  innovation, promoting wellness and accessibility to healthcare
                  for all.
                </p>
              </div>
            </div>
            <div className="card flx33 mb16 df">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Values</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Guided by compassion, integrity, collaboration, and
                  excellence, we uphold the highest ethical standards, work
                  collaboratively, and continuously innovate to provide
                  outstanding patient care.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="our-mission-secion">
          <div className="wrapper ptb48 df">
            <div className="about-content pr48 flx50">
              <span className="about-sub-heading fs18 fc1 fw6 ">
                Our Commitment to Excellence
              </span>
              <h2 className="about-heading fs36 fw6 ptb24 lh48">
                Better Information, Better Health
              </h2>
              <p className="about-desc lh30 v-center fc3 fs18 ">
                At Jeevan Raksha Hospital, we're dedicated to providing
                tailored, high-quality healthcare. Our experienced team
                prioritizes your well-being.
              </p>
              <div className="df fww">
                <ul className="lh30 flx50 pt24">
                  <FaUserDoctor className="fs26 fc1" />
                  <li>
                    EXPERT MEDICAL STAFF
                    <p>
                      Skilled doctors and nurses providing personalized care and
                      expertise.
                    </p>
                  </li>
                </ul>
                <ul className="lh30 flx50 pt24">
                  <FaFlask className="fs26 fc1" />
                  <li>
                    SUFFICIENT LAB TESTS
                    <p>
                      Equipped with cutting-edge technology, offering a wide
                      range of diagnostic tests for accurate results.
                    </p>
                  </li>
                </ul>
              </div>
              <div className="df fww">
                <ul className="lh30 flx50 pt24">
                  <FaBaby className="fs26 fc1" />
                  <li>
                    PEDIATRIC CARE
                    <p>
                      Specialized unit provides compassionate care for children,
                      ensuring their health and well-being.
                    </p>
                  </li>
                </ul>
                <ul className="lh30 flx50 pt24">
                  <FaUserDoctor className="fs26 fc1" />
                  <li>
                    MATERNITY SERVICES
                    <p>
                      Comprehensive maternity services from prenatal care to
                      delivery, focusing on safety and comfort.
                    </p>
                  </li>
                </ul>
              </div>
            </div>
            <div className="about-faq2 br24 flx50 ofh">
              <img
                src="/images/mission-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className="w100"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
