import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { FaAngleRight, FaCheckCircle, FaDotCircle } from "react-icons/fa";
import { FaUserDoctor } from "react-icons/fa6";
import { FaCheck } from "react-icons/fa";
import { FaFlask } from "react-icons/fa";
import { FaBaby } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Jeevan Raksha - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="hero v-center about-inside pr">
          <div className="overlay-inside"></div>
          <div className="wrapper box-center jcs pr zi2">
            <div className="about-hero tac">
              <h1 className="fs38 fw7 mt8 fs30 fw7 lh24 fc4 mb32">About Us</h1>
              <ul className="df ttu box-center fc4">
                <li className="v-center mr16 fs14">
                  <Link href="/" previewlistener="true">
                    HOME
                  </Link>
                </li>
                <li>
                  <FaAngleRight />
                </li>
                <li className="v-center fs14 ml16">About</li>
              </ul>
            </div>
          </div>
        </div>
        <secion className="about-main-secion ">
          <div className="wrapper ptb48 df">
            <div className="about-faq flx48 br24 ofh mtb8">
              <img
                src="/images/about-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className=" w100"
              />
            </div>
            <div className="about-text pl48">
              <div className="about-content">
                <span className="about-sub-heading fs18 fc1 fw6 ">
                  About Us
                </span>
                <h2 className="about-heading fs36 fw6 ptb24 lh48">
                  Short Story About Fovia Clinic Since 1999
                </h2>
                <p className="about-desc lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Quis ipsum suspendisse ultrices gravida. Risus commodo viverra
                  maecenas accumsan lacus vel facilisis.
                </p>
                <ul className="about-list lh30 pt24">
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> Scientific Skills For
                    getting a better result
                  </li>
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> Communication Skills to
                    getting in touch
                  </li>
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> A Career Overview
                    opportunity Available
                  </li>
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> A good Work Environment
                    For work
                  </li>
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> Scientific Skills For
                    getting a better result
                  </li>
                  <li className="v-center">
                    <FaDotCircle className="fc1 mr8" /> Communication Skills to
                    getting in touch
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </secion>
        <section className="our-vision-area ptb48">
          <div className="card-container wrapper df fww">
            <div className="card flx33 mb16">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16 ">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Quis ipsum suspendisse.
                </p>
              </div>
            </div>
            <div className="card flx33 mb16">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Quis ipsum suspendisse.
                </p>
              </div>
            </div>
            <div className="card flx33 mb16">
              <div className="single-vision-box box-sd1 p24 mlr12">
                <div className="fs36 fc1 pb16">
                  <FaCheckCircle />
                </div>
                <h3 className="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                <p className="lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Quis ipsum suspendisse.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="our-mission-secion">
          <div className="wrapper ptb48 df">
            <div className="about-content pr48">
              <span className="about-sub-heading fs18 fc1 fw6 ">
                Our Mission & Vision
              </span>
              <h2 className="about-heading fs36 fw6 ptb24 lh48">
                Better Information, Better Health
              </h2>
              <p className="about-desc lh30 v-center fc3 fs18 ">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <div className="df">
                <ul className="lh30 pt24">
                  <FaUserDoctor className="fs26 fc1" />
                  <li>
                    PROFESSIONAL STAFF
                    <p>
                      Lorem ipsum dolor sit amet sit, consectetur adipiscing
                      elit.
                    </p>
                  </li>
                </ul>
                <ul className="lh30 pt24">
                  <FaFlask className="fs26 fc1" />
                  <li>
                    SUFFICIENT LAB TESTS
                    <p>
                      Lorem ipsum dolor sit amet sit, consectetur adipiscing
                      elit.
                    </p>
                  </li>
                </ul>
              </div>
              <div className="df">
                <ul className="lh30 pt24">
                  <FaBaby className="fs26 fc1" />
                  <li>
                    NEWBORN CARE
                    <p>
                      Lorem ipsum dolor sit amet sit, consectetur adipiscing
                      elit.
                    </p>
                  </li>
                </ul>
                <ul className="lh30 pt24">
                  <FaUserDoctor className="fs26 fc1" />
                  <li>
                    Delivery
                    <p>
                      Lorem ipsum dolor sit amet sit, consectetur adipiscing
                      elit.
                    </p>
                  </li>
                </ul>
              </div>
            </div>
            <div className="about-faq2 br24 ofh">
              <img
                src="/images/mission-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className="w100"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
