import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { HiBuildingOffice } from "react-icons/hi2";
import { HiOutlineMail } from "react-icons/hi";
import { IoCall } from "react-icons/io5";
import { FaHospitalSymbol, FaAngleRight } from "react-icons/fa";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jeevan Raksha - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="hero v-center contact-inside pr">
          <div className="overlay-inside"></div>
          <div className="wrapper box-center jcs pr zi2">
            <div className="about-hero tac">
              <h1 className="fs38 fw7 mt8 fs30 fw7 lh24 fc4 mb32">
                Contact Us
              </h1>
              <ul className="df ttu box-center fc4">
                <li className="v-center mr16 fs14">
                  <Link href="/" previewlistener="true">
                    HOME
                  </Link>
                </li>
                <li>
                  <FaAngleRight />
                </li>
                <li className="v-center fs14 ml16">Contact Us</li>
              </ul>
            </div>
          </div>
        </div>
        <section className="wrapper ptb48">
          <div className="get-in-touch df mb48 ">
            <div className="get-in-touch-heading flx60">
              <div className="section-container mr48">
                <h2 className="section-heading fs36 lh58 fw6 ff2 mr48 pt8">
                  Reach Out to Us
                </h2>
                <p className="section-text fs16 fw4 lh30 fc3 mt16 pb32 pr40 flx1 pr aft btm-line">
                Questions? Concerns? Need to schedule an appointment? Contact us today! Our compassionate team is here to provide prompt assistance tailored to your needs. Reach out via phone, email, or our online form. Your journey to better health starts here.
                </p>
                <div className="contact-container df ais w100 pt16">
                  <div className="card-column-2 flx50">
                    <div className="card mt24 df ">
                      <div className="card-icon br50 bg1 h64 w64 box-center mr16">
                        <HiBuildingOffice className="fs36 fc4" />
                      </div>
                      <div className="card-heading df fdc fww flx1">
                        <h3 className="fs24 fw6 lh34">Head Office</h3>
                        <p className="card-text fw5 lh30 fc6">
                          Pocket 8A, Plot No.8, near sbi bank, Sector 15,
                          Rohini, New Delhi, Delhi, 110085
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="card-column-2 flx50">
                    <div className="card mt24 df ">
                      <div className="card-icon br50 bg1 h64 w64 box-center mr16">
                        <IoCall className="fs36 fc4" />
                      </div>
                      <div className="card-heading df fdc fww flx1">
                        <h3 className="fs24 fw6 lh34">Call Us</h3>
                        <p className="card-text fw5 lh30 fc6">
                          Phone : +91 - 7678356232 
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="contact-container df ais w100 mb32 pt16">
                  <div className="card-column-2 flx50">
                    <div className="card mt24 df ">
                      <div className="card-icon br50 bg1 h64 w64 box-center mr16">
                        <HiOutlineMail className="fs36 fc4" />
                      </div>
                      <div className="card-heading df fdc fww flx1">
                        <h3 className="fs24 fw6 lh34">Email Us</h3>
                        <p className="card-text fw5 lh30 fc6">
                          info@jeevanrakshahospital.com
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="card-column-2 flx50">
                    <div className="card mt24 df ">
                      <div className="card-icon br50 bg1 h64 w64 box-center mr16">
                        <FaHospitalSymbol className="fs36 fc4" />
                      </div>
                      <div className="card-heading df fdc fww flx1">
                        <h3 className="fs24 fw6 lh34">Office Hour</h3>
                        <p className="card-text fw5 lh30 fc6">
                          24*7 Hours Available
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="form-section p32 box-sd2">
              <div className="form-heading">
                <h3 className="fs36 lh34 mtb24 fw5">
                  Feel free to drop us a message
                </h3>
              </div>
              <div className="form mt32">
                <form action="#" method="post">
                  <div className="contact-form df fww mb16">
                    <div className="input-column df fww flx50 mb16">
                      <label className="fw5 mb8 ml84 pl4" for="">
                        Name
                      </label>
                      <input
                        className="w100 pl12 db h48 br8 brd1 mlr4"
                        type="text"
                        placeholder="Name"
                      />
                    </div>

                    <div className="input-column df fww flx50 mb16">
                      <label className="fw5 mb8 ml84 pl4" for="">
                        Phone
                      </label>
                      <br />
                      <input
                        className="w100 pl12 db h48 br8 brd1 mlr4"
                        type="text"
                        placeholder="Phone"
                      />
                    </div>
                    <div className="input-column df fww flx50 mb16">
                      <label className="fw5 mb8 ml84 pl4" for="">
                        Disease
                      </label>
                      <input
                        className=" w100 pl12 db h48 br8 brd1 mlr4"
                        type="text"
                        placeholder="Disease"
                      />
                    </div>
                    <div className="input-column df fww flx50 mb16">
                      <label className="fw5 mb8 ml84 pl4" for="">
                        Doctor Name
                      </label>
                      <input
                        className="w100 pl12 db h48 br8 brd1 mlr4"
                        type="text"
                        placeholder="Doctor Name..."
                      />
                    </div>
                    <div className="df fww flx100 pr8">
                      <label className="fw5 mb8 ml84 pl4" for="">
                        Message
                      </label>
                      <textarea
                        className="flx100 pl12 pt8 mb8 db h80 br8 brd1 mlr4 "
                        name="message"
                        id=""
                        rows="7"
                        placeholder="Write a Message"
                      ></textarea>
                    </div>
                    <div className="submit-btn h48 br8 v-center jcc plr24 mt8 cp fc4 bg1">
                      Submit Now
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
