import Head from "next/head";
import { Inter } from "next/font/google";
import { FaAngleRight } from "react-icons/fa";
import Link from "next/link";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export default function Delivery() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="hero v-center delivery-inside pr">
          <div className="overlay-inside"></div>
          <div className="wrapper box-center jcs pr zi2">
            <div className="about-hero tac">
              <h1 className="fs26 fw6 mt8 fs30 fw7 lh24 fc4 mb24">
                Medical coding Outsourcing Services
              </h1>
              <ul className="df ttu box-center fc4">
                <li className="v-center mr16 fs14">
                  <Link href="/" previewlistener="true">
                    HOME
                  </Link>
                </li>
                <li>
                  <FaAngleRight />
                </li>
                <li className="v-center fs14 ml16">Delivery</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="wrapper plr48 ">
          <div className="services-details-img">
            <Image
              src="/images/delivery-inside.jpg"
              width={100}
              layout="responsive"
              height={100}
              alt="delivery-inside image"
              className="mtb24"
            />
            <h2 className="fs26 fc1 fw6 mb16">
              Our hospital always provide good services
            </h2>
            <p className="lh24 v-center fc3 fs18 ">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </p>
            <p className="lh24 v-center fc3 fs18 mt24">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </p>
          </div>
          <div className="df mt32">
            <div className="flx1 mr24">
              <img
                src="/images/signup-bg.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className="mtb24 w100"
              />
            </div>
            <div className="flx66">
              <div className="mt24">
                <h2 className="fs26 fc1 fw6 mb16 lh30">
                  We always take care our patient
                </h2>
                <p className="lh24 v-center fc3 fs18 mb16">
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                  Architecto blanditiis obcaecati veritatis magnam pariatur
                  molestiae in maxime. Animi quae vitae in inventore. Totam
                  mollitia aspernatur provident veniam aperiam placeat impedit!
                  Lorem ipsum dolor sit amet,excepturi iure autem nemo ducimus
                  temporibus facere, est eum voluptatem, culpa optio fugit
                  assumenda quod? Praesentium.
                </p>
                <p className="lh24 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Id,
                  laudantium ullam, iure distinctio officia libero voluptatem
                  obcaecati vero deleniti minima nemo itaque alias nisi eveniet
                  soluta architecto quae laboriosam unde.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
